# Shell variables
# Generated by 'wal'
wallpaper='/home/chararch/.dotfiles/Pictures/wallpapers/plain-wallpaper.png'

# Special
background='#0A0A0A'
foreground='#dc91ad'
cursor='#dc91ad'

# Colors
color0='#0A0A0A'
color1='#DC6018'
color2='#D95534'
color3='#A2105D'
color4='#8D1365'
color5='#AD1B60'
color6='#CD3C5C'
color7='#dc91ad'
color8='#9a6579'
color9='#DC6018'
color10='#D95534'
color11='#A2105D'
color12='#8D1365'
color13='#AD1B60'
color14='#CD3C5C'
color15='#dc91ad'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
