--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chararch/Pictures/wallpapers/hyprfog-2.png"

-- Special
background="#0A121B"
foreground="#77e0e0"
cursor="#77e0e0"

-- Colors
color0="#0A121B"
color1="#066769"
color2="#05827D"
color3="#056D93"
color4="#03A1A7"
color5="#02A2D3"
color6="#00AFED"
color7="#77e0e0"
color8="#539c9c"
color9="#066769"
color10="#05827D"
color11="#056D93"
color12="#03A1A7"
color13="#02A2D3"
color14="#00AFED"
color15="#77e0e0"
