# Shell variables
# Generated by 'wal'
wallpaper='/home/chararch/.dotfiles/Pictures/wallpapers/minimal_gradient.png'

# Special
background='#0b0232'
foreground='#7ca3cb'
cursor='#7ca3cb'

# Colors
color0='#0b0232'
color1='#B00068'
color2='#C5006B'
color3='#0E3887'
color4='#0D4494'
color5='#0C4897'
color6='#0C4A99'
color7='#7ca3cb'
color8='#56728e'
color9='#B00068'
color10='#C5006B'
color11='#0E3887'
color12='#0D4494'
color13='#0C4897'
color14='#0C4A99'
color15='#7ca3cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
