--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chararch/.dotfiles/Pictures/wallpapers/distantmountains.jpeg"

-- Special
background="#040916"
foreground="#b0bbd5"
cursor="#b0bbd5"

-- Colors
color0="#040916"
color1="#314674"
color2="#42587B"
color3="#38518A"
color4="#3D629D"
color5="#4E68A0"
color6="#647FC0"
color7="#b0bbd5"
color8="#7b8295"
color9="#314674"
color10="#42587B"
color11="#38518A"
color12="#3D629D"
color13="#4E68A0"
color14="#647FC0"
color15="#b0bbd5"
