--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chararch/Pictures/wallpapers/wide_tokyonight_lines.png"

-- Special
background="#0f1016"
foreground="#d4c4f2"
cursor="#d4c4f2"

-- Colors
color0="#0f1016"
color1="#8F7AC1"
color2="#45A5AF"
color3="#2AC3DE"
color4="#2AC5E0"
color5="#73DACA"
color6="#9E86D4"
color7="#d4c4f2"
color8="#9489a9"
color9="#8F7AC1"
color10="#45A5AF"
color11="#2AC3DE"
color12="#2AC5E0"
color13="#73DACA"
color14="#9E86D4"
color15="#d4c4f2"
