# Shell variables
# Generated by 'wal'
wallpaper='/home/charlie/.dotfiles/Pictures/wallpapers/colorful-planets.jpg'

# Special
background='#0d0d12'
foreground='#b5def6'
cursor='#b5def6'

# Colors
color0='#0d0d12'
color1='#FCA163'
color2='#B06D83'
color3='#D06F86'
color4='#F7758D'
color5='#678BB1'
color6='#79A2F5'
color7='#b5def6'
color8='#7e9bac'
color9='#FCA163'
color10='#B06D83'
color11='#D06F86'
color12='#F7758D'
color13='#678BB1'
color14='#79A2F5'
color15='#b5def6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
