import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[shell]
program = "/bin/fish"
args = ["-l"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
blur = true
opacity = 0.98

[font]
size = 10.75

[cursor]
style = { shape = "Beam", blinking = "Always" }

[terminal]
osc52 = "CopyPaste"
