theme = "catppuccin_mocha"

# theme = "catppuccin_macchiato"

[editor]
mouse = true
auto-format = false
auto-save = true
line-number = "absolute"
cursorline = true
color-modes = true
bufferline = "multiple"
lsp.display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

# [editor.statusline]
# left = ["mode", "spinner"]
# center = ["file-name"]
# right = ["file-encoding", "file-line-ending", "file-type"]
# separator = "│"
# mode.normal = "NORMAL"
# mode.insert = "INSERT"
# mode.select = "SELECT"

[editor.statusline]
left = [ "mode", "spinner", "diagnostics" ]
center = [ "file-name" ]
right = [ "position", "total-line-numbers", "file-type" ]
separator = "| "
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
g = { a = "code_action" }
X = "extend_line_up"
D = "delete_char_backward"

[keys.normal."+"]
m = ":run-shell-command make"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo check"
r = ":run-shell-command cargo run"
p = ":run-shell-command pwd"

